// Seed a D1 database from a local checkout of the notes repo (schema v2).
//
//   npx vite-node scripts/seed-d1.ts -- <notes-dir> <out.sql>
//
// Runs each note through the real ingest (`docToGraph`) and emits an
// idempotent SQL file of node + link rows for `wrangler d1 execute --file`.
// Cross-note block-id collisions are only REPORTED here — parse() remints
// duplicates it sees within one document, and an accidental cross-note share
// would otherwise silently become a multi-parent node; a full replica push
// then replaces this seed wholesale anyway.
// vite-node applies the app's browser node-polyfills, which shim node:fs into
// a stub — reach the real builtins the same way sql-node-test-driver does.
const { readdirSync, readFileSync, writeFileSync } = process.getBuiltinModule("node:fs")
const path = process.getBuiltinModule("node:path")
import { docToGraph, findCrossNoteIdCollisions } from "../src/data/graph"

const [notesDir, outFile] = process.argv.slice(2).filter((a) => a !== "--")
if (!notesDir || !outFile) {
  console.error("usage: npx vite-node scripts/seed-d1.ts -- <notes-dir> <out.sql>")
  process.exit(2)
}

// Strings are emitted as hex blob literals cast to TEXT: the generated SQL
// then contains no quotes or newlines, so naive statement splitters (wrangler
// --command) can never break a statement mid-string.
const q = (v: string | number | null): string =>
  v === null
    ? "NULL"
    : typeof v === "number"
      ? String(v)
      : `CAST(X'${Buffer.from(v, "utf8").toString("hex")}' AS TEXT)`

const notes: Record<string, string> = {}
for (const f of readdirSync(notesDir)) {
  if (f.endsWith(".md")) notes[f.slice(0, -3)] = readFileSync(path.join(notesDir, f), "utf8")
}

const collisions = findCrossNoteIdCollisions(notes)
if (collisions.length > 0) {
  console.warn("cross-note block-id collisions (first note keeps the id; fix the others):")
  for (const c of collisions) console.warn(`  ${JSON.stringify(c)}`)
}

const lines: string[] = [
  "-- Generated by scripts/seed-d1.ts — idempotent full replace (schema v2).",
  "DELETE FROM link;",
  "DELETE FROM nodes;",
]

// One seed-time stamp for every row: a device holding an older cursor then
// picks the whole re-seed up on its next since-pull.
const seedTime = Date.now()

let nodeCount = 0
let linkCount = 0
const nodeLines: string[] = []
const linkLines: string[] = []
for (const id of Object.keys(notes).sort((a, b) => a.localeCompare(b))) {
  const { nodes: nodeRows, links: linkRows } = docToGraph(id, notes[id], seedTime)
  for (const n of nodeRows) {
    nodeCount++
    // OR REPLACE: a colliding block id (reported above) keeps the last write
    // instead of aborting the whole seed.
    nodeLines.push(
      `INSERT OR REPLACE INTO nodes (id, type, text, props, updated_at) VALUES (${q(n.id)}, ${q(n.type)}, ${q(n.text)}, ${q(n.props)}, ${q(n.updated_at)});`,
    )
  }
  for (const l of linkRows) {
    linkCount++
    linkLines.push(
      `INSERT OR REPLACE INTO link (source_id, destination_id, kind, sort_key, updated_at) VALUES (${q(l.source_id)}, ${q(l.destination_id)}, ${q(l.kind)}, ${q(l.sort_key)}, ${q(l.updated_at)});`,
    )
  }
}
// Every node row before any link row — the link table's foreign keys.
lines.push(...nodeLines, ...linkLines)
lines.push(
  `INSERT OR REPLACE INTO meta (key, value) VALUES ('replica_cursor', ${q(String(seedTime))});`,
)

writeFileSync(outFile, lines.join("\n") + "\n")
console.log(
  `seed: ${Object.keys(notes).length} notes → ${nodeCount} nodes, ${linkCount} links → ${outFile}`,
)
