// Seed a D1 database from a local checkout of the notes repo.
//
//   npx vite-node scripts/seed-d1.ts -- <notes-dir> <out.sql>
//
// Builds a path-keyed file map (notes + .ruminate/view-state sidecars), runs
// the exact transform a live replica push uses (`buildReplicaNoteEntry`), and
// emits an idempotent SQL file for `wrangler d1 execute --file`. Cross-note
// block-id collisions are only REPORTED here — parse() remints duplicates it
// sees, and the app's own ingest re-keys them properly through git on first
// flag-on; a full replica push then replaces this seed wholesale anyway.
// vite-node applies the app's browser node-polyfills, which shim node:fs into
// a stub — reach the real builtins the same way sql-node-test-driver does.
const { readdirSync, readFileSync, writeFileSync } = process.getBuiltinModule("node:fs")
const path = process.getBuiltinModule("node:path")
import { findCrossNoteIdCollisions } from "../src/data/doc-to-rows"
import { buildReplicaNoteEntry } from "../src/data/replica-sync"

const [notesDir, outFile] = process.argv.slice(2).filter((a) => a !== "--")
if (!notesDir || !outFile) {
  console.error("usage: npx vite-node scripts/seed-d1.ts -- <notes-dir> <out.sql>")
  process.exit(2)
}

// Strings are emitted as hex blob literals cast to TEXT: the generated SQL
// then contains no quotes or newlines, so naive statement splitters (wrangler
// --command) can never break a statement mid-string.
const q = (v: string | number | null): string =>
  v === null
    ? "NULL"
    : typeof v === "number"
      ? String(v)
      : `CAST(X'${Buffer.from(v, "utf8").toString("hex")}' AS TEXT)`

// Path-keyed file map, exactly the shape the app's worktree walk produces.
const files: Record<string, string> = {}
const ids: string[] = []
for (const f of readdirSync(notesDir)) {
  if (f.endsWith(".md")) {
    files[f] = readFileSync(path.join(notesDir, f), "utf8")
    ids.push(f.slice(0, -3))
  }
}
const vsDir = path.join(notesDir, ".ruminate", "view-state")
try {
  for (const f of readdirSync(vsDir)) {
    if (f.endsWith(".json")) {
      files[`.ruminate/view-state/${f}`] = readFileSync(path.join(vsDir, f), "utf8")
    }
  }
} catch {
  // no view-state dir — fine
}

const noteContents = Object.fromEntries(ids.map((id) => [id, files[`${id}.md`]]))
const collisions = findCrossNoteIdCollisions(noteContents)
if (collisions.length > 0) {
  console.warn("cross-note block-id collisions (app re-keys these properly on first ingest):")
  for (const c of collisions) console.warn(`  ${JSON.stringify(c)}`)
}

const lines: string[] = [
  "-- Generated by scripts/seed-d1.ts — idempotent full replace.",
  "DELETE FROM links;",
  "DELETE FROM blocks;",
  "DELETE FROM view_state;",
  "DELETE FROM notes;",
]

let blockCount = 0
let linkCount = 0
let viewStateCount = 0
for (const id of ids.sort((a, b) => a.localeCompare(b))) {
  const entry = buildReplicaNoteEntry(files, id)
  if (!entry) continue
  lines.push(
    `INSERT INTO notes (id, content, updated_at) VALUES (${q(entry.note.id)}, ${q(entry.note.content)}, ${q(entry.note.updated_at)});`,
  )
  for (const b of entry.blocks) {
    blockCount++
    lines.push(
      `INSERT INTO blocks (id, note_id, parent_id, position, content) VALUES (${q(b.id)}, ${q(b.note_id)}, ${q(b.parent_id)}, ${q(b.position)}, ${q(b.content)});`,
    )
  }
  for (const l of entry.links) {
    linkCount++
    lines.push(
      `INSERT INTO links (from_block, to_note, to_block, kind) VALUES (${q(l.from_block)}, ${q(l.to_note)}, ${q(l.to_block)}, ${q(l.kind)});`,
    )
  }
  if (entry.view_state && entry.view_state.length > 0) {
    viewStateCount++
    lines.push(
      `INSERT INTO view_state (note_id, collapsed) VALUES (${q(id)}, ${q(JSON.stringify(entry.view_state))});`,
    )
  }
}
lines.push(
  `INSERT OR REPLACE INTO meta (key, value) VALUES ('replica_cursor', ${q(String(Date.now()))});`,
)

writeFileSync(outFile, lines.join("\n") + "\n")
console.log(
  `seed: ${ids.length} notes, ${blockCount} blocks, ${linkCount} links, ${viewStateCount} view states → ${outFile}`,
)
