/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRootRouteImport } from './routes/_appRoot'
import { Route as AppRootIndexRouteImport } from './routes/_appRoot.index'
import { Route as AppRootAdminRouteImport } from './routes/_appRoot.admin'
import { Route as AppRootChangelogRouteImport } from './routes/_appRoot.changelog'
import { Route as AppRootSettingsRouteImport } from './routes/_appRoot.settings'
import { Route as AppRootBoardsSplatRouteImport } from './routes/_appRoot.boards.$'
import { Route as AppRootCalendarIndexRouteImport } from './routes/_appRoot.calendar.index'
import { Route as AppRootCalendarSplatRouteImport } from './routes/_appRoot.calendar.$'
import { Route as AppRootInviteTokenRouteImport } from './routes/_appRoot.invite.$token'
import { Route as AppRootNotesIndexRouteImport } from './routes/_appRoot.notes.index'
import { Route as AppRootNotesSplatRouteImport } from './routes/_appRoot.notes_.$'
import { Route as AppRootSettingsIndexRouteImport } from './routes/_appRoot.settings.index'
import { Route as AppRootSettingsPageRouteImport } from './routes/_appRoot.settings.$page'
import { Route as AppRootViewsIndexRouteImport } from './routes/_appRoot.views.index'
import { Route as AppRootViewsSplatRouteImport } from './routes/_appRoot.views_.$'

const AppRootRoute = AppRootRouteImport.update({
  id: '/_appRoot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootIndexRoute = AppRootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootAdminRoute = AppRootAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootChangelogRoute = AppRootChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootSettingsRoute = AppRootSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootBoardsSplatRoute = AppRootBoardsSplatRouteImport.update({
  id: '/boards/$',
  path: '/boards/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootCalendarIndexRoute = AppRootCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootCalendarSplatRoute = AppRootCalendarSplatRouteImport.update({
  id: '/calendar/$',
  path: '/calendar/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootInviteTokenRoute = AppRootInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootNotesIndexRoute = AppRootNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootNotesSplatRoute = AppRootNotesSplatRouteImport.update({
  id: '/notes_/$',
  path: '/notes/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootSettingsIndexRoute = AppRootSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRootSettingsRoute,
} as any)
const AppRootSettingsPageRoute = AppRootSettingsPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppRootSettingsRoute,
} as any)
const AppRootViewsIndexRoute = AppRootViewsIndexRouteImport.update({
  id: '/views/',
  path: '/views/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootViewsSplatRoute = AppRootViewsSplatRouteImport.update({
  id: '/views_/$',
  path: '/views/$',
  getParentRoute: () => AppRootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRootIndexRoute
  '/admin': typeof AppRootAdminRoute
  '/changelog': typeof AppRootChangelogRoute
  '/settings': typeof AppRootSettingsRouteWithChildren
  '/boards/$': typeof AppRootBoardsSplatRoute
  '/calendar/$': typeof AppRootCalendarSplatRoute
  '/invite/$token': typeof AppRootInviteTokenRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/settings/$page': typeof AppRootSettingsPageRoute
  '/views/$': typeof AppRootViewsSplatRoute
  '/calendar/': typeof AppRootCalendarIndexRoute
  '/notes/': typeof AppRootNotesIndexRoute
  '/settings/': typeof AppRootSettingsIndexRoute
  '/views/': typeof AppRootViewsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppRootAdminRoute
  '/changelog': typeof AppRootChangelogRoute
  '/': typeof AppRootIndexRoute
  '/boards/$': typeof AppRootBoardsSplatRoute
  '/calendar/$': typeof AppRootCalendarSplatRoute
  '/invite/$token': typeof AppRootInviteTokenRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/settings/$page': typeof AppRootSettingsPageRoute
  '/views/$': typeof AppRootViewsSplatRoute
  '/calendar': typeof AppRootCalendarIndexRoute
  '/notes': typeof AppRootNotesIndexRoute
  '/settings': typeof AppRootSettingsIndexRoute
  '/views': typeof AppRootViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appRoot': typeof AppRootRouteWithChildren
  '/_appRoot/admin': typeof AppRootAdminRoute
  '/_appRoot/changelog': typeof AppRootChangelogRoute
  '/_appRoot/settings': typeof AppRootSettingsRouteWithChildren
  '/_appRoot/': typeof AppRootIndexRoute
  '/_appRoot/boards/$': typeof AppRootBoardsSplatRoute
  '/_appRoot/calendar/$': typeof AppRootCalendarSplatRoute
  '/_appRoot/invite/$token': typeof AppRootInviteTokenRoute
  '/_appRoot/notes_/$': typeof AppRootNotesSplatRoute
  '/_appRoot/settings/$page': typeof AppRootSettingsPageRoute
  '/_appRoot/views_/$': typeof AppRootViewsSplatRoute
  '/_appRoot/calendar/': typeof AppRootCalendarIndexRoute
  '/_appRoot/notes/': typeof AppRootNotesIndexRoute
  '/_appRoot/settings/': typeof AppRootSettingsIndexRoute
  '/_appRoot/views/': typeof AppRootViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/settings'
    | '/boards/$'
    | '/calendar/$'
    | '/invite/$token'
    | '/notes/$'
    | '/settings/$page'
    | '/views/$'
    | '/calendar/'
    | '/notes/'
    | '/settings/'
    | '/views/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/changelog'
    | '/'
    | '/boards/$'
    | '/calendar/$'
    | '/invite/$token'
    | '/notes/$'
    | '/settings/$page'
    | '/views/$'
    | '/calendar'
    | '/notes'
    | '/settings'
    | '/views'
  id:
    | '__root__'
    | '/_appRoot'
    | '/_appRoot/admin'
    | '/_appRoot/changelog'
    | '/_appRoot/settings'
    | '/_appRoot/'
    | '/_appRoot/boards/$'
    | '/_appRoot/calendar/$'
    | '/_appRoot/invite/$token'
    | '/_appRoot/notes_/$'
    | '/_appRoot/settings/$page'
    | '/_appRoot/views_/$'
    | '/_appRoot/calendar/'
    | '/_appRoot/notes/'
    | '/_appRoot/settings/'
    | '/_appRoot/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appRoot': {
      id: '/_appRoot'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appRoot/': {
      id: '/_appRoot/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppRootIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/admin': {
      id: '/_appRoot/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppRootAdminRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/changelog': {
      id: '/_appRoot/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppRootChangelogRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/settings': {
      id: '/_appRoot/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppRootSettingsRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/boards/$': {
      id: '/_appRoot/boards/$'
      path: '/boards/$'
      fullPath: '/boards/$'
      preLoaderRoute: typeof AppRootBoardsSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/calendar/': {
      id: '/_appRoot/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppRootCalendarIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/calendar/$': {
      id: '/_appRoot/calendar/$'
      path: '/calendar/$'
      fullPath: '/calendar/$'
      preLoaderRoute: typeof AppRootCalendarSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/invite/$token': {
      id: '/_appRoot/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppRootInviteTokenRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/notes/': {
      id: '/_appRoot/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppRootNotesIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/notes_/$': {
      id: '/_appRoot/notes_/$'
      path: '/notes/$'
      fullPath: '/notes/$'
      preLoaderRoute: typeof AppRootNotesSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/settings/': {
      id: '/_appRoot/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppRootSettingsIndexRouteImport
      parentRoute: typeof AppRootSettingsRoute
    }
    '/_appRoot/settings/$page': {
      id: '/_appRoot/settings/$page'
      path: '/$page'
      fullPath: '/settings/$page'
      preLoaderRoute: typeof AppRootSettingsPageRouteImport
      parentRoute: typeof AppRootSettingsRoute
    }
    '/_appRoot/views/': {
      id: '/_appRoot/views/'
      path: '/views'
      fullPath: '/views/'
      preLoaderRoute: typeof AppRootViewsIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/views_/$': {
      id: '/_appRoot/views_/$'
      path: '/views/$'
      fullPath: '/views/$'
      preLoaderRoute: typeof AppRootViewsSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
  }
}

interface AppRootSettingsRouteChildren {
  AppRootSettingsPageRoute: typeof AppRootSettingsPageRoute
  AppRootSettingsIndexRoute: typeof AppRootSettingsIndexRoute
}

const AppRootSettingsRouteChildren: AppRootSettingsRouteChildren = {
  AppRootSettingsPageRoute: AppRootSettingsPageRoute,
  AppRootSettingsIndexRoute: AppRootSettingsIndexRoute,
}

const AppRootSettingsRouteWithChildren = AppRootSettingsRoute._addFileChildren(
  AppRootSettingsRouteChildren,
)

interface AppRootRouteChildren {
  AppRootAdminRoute: typeof AppRootAdminRoute
  AppRootChangelogRoute: typeof AppRootChangelogRoute
  AppRootSettingsRoute: typeof AppRootSettingsRouteWithChildren
  AppRootIndexRoute: typeof AppRootIndexRoute
  AppRootBoardsSplatRoute: typeof AppRootBoardsSplatRoute
  AppRootCalendarSplatRoute: typeof AppRootCalendarSplatRoute
  AppRootInviteTokenRoute: typeof AppRootInviteTokenRoute
  AppRootNotesSplatRoute: typeof AppRootNotesSplatRoute
  AppRootViewsSplatRoute: typeof AppRootViewsSplatRoute
  AppRootCalendarIndexRoute: typeof AppRootCalendarIndexRoute
  AppRootNotesIndexRoute: typeof AppRootNotesIndexRoute
  AppRootViewsIndexRoute: typeof AppRootViewsIndexRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootAdminRoute: AppRootAdminRoute,
  AppRootChangelogRoute: AppRootChangelogRoute,
  AppRootSettingsRoute: AppRootSettingsRouteWithChildren,
  AppRootIndexRoute: AppRootIndexRoute,
  AppRootBoardsSplatRoute: AppRootBoardsSplatRoute,
  AppRootCalendarSplatRoute: AppRootCalendarSplatRoute,
  AppRootInviteTokenRoute: AppRootInviteTokenRoute,
  AppRootNotesSplatRoute: AppRootNotesSplatRoute,
  AppRootViewsSplatRoute: AppRootViewsSplatRoute,
  AppRootCalendarIndexRoute: AppRootCalendarIndexRoute,
  AppRootNotesIndexRoute: AppRootNotesIndexRoute,
  AppRootViewsIndexRoute: AppRootViewsIndexRoute,
}

const AppRootRouteWithChildren =
  AppRootRoute._addFileChildren(AppRootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
