/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRootImport } from './routes/_appRoot'
import { Route as AppRootIndexImport } from './routes/_appRoot.index'
import { Route as AppRootSettingsImport } from './routes/_appRoot.settings'
import { Route as AppRootAdminImport } from './routes/_appRoot.admin'
import { Route as AppRootNotesIndexImport } from './routes/_appRoot.notes.index'
import { Route as AppRootNotesSplatImport } from './routes/_appRoot.notes_.$'

// Create/Update Routes

const AppRootRoute = AppRootImport.update({
  id: '/_appRoot',
  getParentRoute: () => rootRoute,
} as any)

const AppRootIndexRoute = AppRootIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootSettingsRoute = AppRootSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootAdminRoute = AppRootAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootNotesIndexRoute = AppRootNotesIndexImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRootRoute,
} as any)

const AppRootNotesSplatRoute = AppRootNotesSplatImport.update({
  id: '/notes_/$',
  path: '/notes/$',
  getParentRoute: () => AppRootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appRoot': {
      id: '/_appRoot'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRootImport
      parentRoute: typeof rootRoute
    }
    '/_appRoot/admin': {
      id: '/_appRoot/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppRootAdminImport
      parentRoute: typeof AppRootImport
    }
    '/_appRoot/settings': {
      id: '/_appRoot/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppRootSettingsImport
      parentRoute: typeof AppRootImport
    }
    '/_appRoot/': {
      id: '/_appRoot/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppRootIndexImport
      parentRoute: typeof AppRootImport
    }
    '/_appRoot/notes_/$': {
      id: '/_appRoot/notes_/$'
      path: '/notes/$'
      fullPath: '/notes/$'
      preLoaderRoute: typeof AppRootNotesSplatImport
      parentRoute: typeof AppRootImport
    }
    '/_appRoot/notes/': {
      id: '/_appRoot/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppRootNotesIndexImport
      parentRoute: typeof AppRootImport
    }
  }
}

// Create and export the route tree

interface AppRootRouteChildren {
  AppRootAdminRoute: typeof AppRootAdminRoute
  AppRootSettingsRoute: typeof AppRootSettingsRoute
  AppRootIndexRoute: typeof AppRootIndexRoute
  AppRootNotesSplatRoute: typeof AppRootNotesSplatRoute
  AppRootNotesIndexRoute: typeof AppRootNotesIndexRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootAdminRoute: AppRootAdminRoute,
  AppRootSettingsRoute: AppRootSettingsRoute,
  AppRootIndexRoute: AppRootIndexRoute,
  AppRootNotesSplatRoute: AppRootNotesSplatRoute,
  AppRootNotesIndexRoute: AppRootNotesIndexRoute,
}

const AppRootRouteWithChildren =
  AppRootRoute._addFileChildren(AppRootRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRootRouteWithChildren
  '/admin': typeof AppRootAdminRoute
  '/settings': typeof AppRootSettingsRoute
  '/': typeof AppRootIndexRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/notes': typeof AppRootNotesIndexRoute
}

export interface FileRoutesByTo {
  '/admin': typeof AppRootAdminRoute
  '/settings': typeof AppRootSettingsRoute
  '/': typeof AppRootIndexRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/notes': typeof AppRootNotesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_appRoot': typeof AppRootRouteWithChildren
  '/_appRoot/admin': typeof AppRootAdminRoute
  '/_appRoot/settings': typeof AppRootSettingsRoute
  '/_appRoot/': typeof AppRootIndexRoute
  '/_appRoot/notes_/$': typeof AppRootNotesSplatRoute
  '/_appRoot/notes/': typeof AppRootNotesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/admin' | '/settings' | '/' | '/notes/$' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/settings' | '/' | '/notes/$' | '/notes'
  id:
    | '__root__'
    | '/_appRoot'
    | '/_appRoot/admin'
    | '/_appRoot/settings'
    | '/_appRoot/'
    | '/_appRoot/notes_/$'
    | '/_appRoot/notes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_appRoot"
      ]
    },
    "/_appRoot": {
      "filePath": "_appRoot.tsx",
      "children": [
        "/_appRoot/admin",
        "/_appRoot/settings",
        "/_appRoot/",
        "/_appRoot/notes_/$",
        "/_appRoot/notes/"
      ]
    },
    "/_appRoot/admin": {
      "filePath": "_appRoot.admin.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/settings": {
      "filePath": "_appRoot.settings.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/": {
      "filePath": "_appRoot.index.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/notes_/$": {
      "filePath": "_appRoot.notes_.$.tsx",
      "parent": "/_appRoot"
    },
    "/_appRoot/notes/": {
      "filePath": "_appRoot.notes.index.tsx",
      "parent": "/_appRoot"
    }
  }
}
ROUTE_MANIFEST_END */
