import {
  CORPUS_ROOT_ID,
  NOTE_TYPE,
  ROOT_TYPE,
  noteOrderIds,
  sortKeyBetween,
  type GraphSnapshot,
} from "./graph"
import { generateNKeysBetween } from "fractional-indexing"
import { notePropsOps } from "./note-meta"
import type { Op } from "./ops"
import type { NoteId } from "../schema"

/**
 * The **manual note order** — the one the sidebar drags and the notes list
 * reads (docs/graph-storage.md, "Ordering notes").
 *
 * Sibling order for a block is a `sort_key` on the `child` link from its
 * parent, and notes get exactly the same mechanism: the corpus root
 * (`ROOT_TYPE`) holds every manually placed note, and the key on its link
 * says where the note sits. There is no note-specific ordering concept — the
 * keys are the same fractional indices, generated by the same
 * `sortKeyBetween`, which is why moving one note rewrites one link row rather
 * than renumbering the list.
 *
 * The root is **ordering-only**: a note it does not hold is an ordinary note
 * with no manual position, which is what lets the manual order arrive with
 * nothing to backfill. `orderedNoteIds` returns the placed notes; everything
 * else is the caller's fallback band.
 */

/** The ops that put the corpus root in the graph, or none when it is already
 * there. Minted on the first drag rather than at boot, so a corpus nobody has
 * reordered carries no root row at all. */
function ensureRootOps(snapshot: GraphSnapshot): Op[] {
  if (snapshot.nodes.has(CORPUS_ROOT_ID)) return []
  return [{ op: "create", id: CORPUS_ROOT_ID, type: ROOT_TYPE, text: "", props: null }]
}

const isNote = (snapshot: GraphSnapshot, id: string) => snapshot.nodes.get(id)?.type === NOTE_TYPE

/** The key the root's link to each placed note carries. */
function keysByNote(snapshot: GraphSnapshot): Map<string, string> {
  const keys = new Map<string, string>()
  for (const link of snapshot.childLinks.get(CORPUS_ROOT_ID) ?? []) {
    keys.set(link.destination_id, link.sort_key)
  }
  return keys
}

/**
 * The manually placed notes, in their order — live notes only.
 *
 * A delete does not cascade to link rows (`ops-rows.ts`), so the stored order
 * can name a note that is no longer in the graph; such ids are dropped here
 * rather than written out, which keeps deleting a note free of any order
 * bookkeeping.
 */
export function orderedNoteIds(snapshot: GraphSnapshot): NoteId[] {
  return noteOrderIds(snapshot).filter((id) => isNote(snapshot, id))
}

/** Key every note in `live` from scratch, evenly spaced — the first drag on a
 * corpus, where there is no existing order to move within. */
function seedOps(live: NoteId[], snapshot: GraphSnapshot): Op[] {
  const keys = generateNKeysBetween(null, null, live.length)
  return [
    ...ensureRootOps(snapshot),
    ...live.map((id, index): Op => ({
      op: "link",
      source: CORPUS_ROOT_ID,
      destination: id,
      sortKey: keys[index],
    })),
  ]
}

/**
 * The ops that move one note within the manual order. `desired` is the full
 * list of notes in the order they should now sit — what the sidebar drew,
 * with the dragged row at its new index — and `noteId` is the row that moved.
 *
 * In the steady state this is **one link row**: the moved note takes a fresh
 * key between the two it now sits between, and nothing else is touched. Only
 * the first drag on a corpus writes more, because there are no keys yet to
 * move between (`seedOps`).
 *
 * The moved note's `updated_at` is stamped too. The key rides a link row, so
 * the note node would otherwise not register the change at all — and a
 * reorder is an edit to the note's place in the corpus.
 *
 * Note that `reconcileSortKeys` is deliberately not used here. It answers
 * "here is a whole new child order", and its greedy pass keeps the first run
 * of keys it can — so a note dragged to the front would re-key everything it
 * jumped rather than itself. That is right for the editor's doc diff and
 * wrong for a drag, which knows exactly which row moved.
 */
export function moveNoteOps(noteId: NoteId, desired: NoteId[], snapshot: GraphSnapshot): Op[] {
  const live = desired.filter((id) => isNote(snapshot, id))
  const index = live.indexOf(noteId)
  if (index === -1) return []

  const keys = keysByNote(snapshot)
  // Every note but the one being moved needs a key to move between; without
  // that, this is the first drag and the whole list is keyed at once.
  const placed = live.every((id) => id === noteId || keys.get(id) !== undefined)
  if (!placed) return seedOps(live, snapshot)

  const before = index > 0 ? (keys.get(live[index - 1]) ?? null) : null
  const after = index < live.length - 1 ? (keys.get(live[index + 1]) ?? null) : null
  // The neighbours' keys must bracket the gap. They do whenever `desired`
  // keeps the placed notes in their stored order, which a drag does — but a
  // caller that reordered several at once would land here, and re-keying the
  // list is the honest answer rather than a key that cannot be generated.
  if (before !== null && after !== null && before >= after) return seedOps(live, snapshot)
  if (keys.get(noteId) === sortKeyBetween(before, after)) return []

  return [
    ...ensureRootOps(snapshot),
    {
      op: "link",
      source: CORPUS_ROOT_ID,
      destination: noteId,
      sortKey: sortKeyBetween(before, after),
    },
    ...notePropsOps(noteId, {}, snapshot),
  ]
}
